language: php
php: 5.6

cache:
  directories:
  - $HOME/.composer/cache/repo/
  - $TRAVIS_BUILD_DIR/vendor/

branches:
  only:
    - master

matrix:
  fast_finish: true
  allow_failures:
  - php: 7.2
  include:
  - stage: test
    env: JOB=test
    install: make install
    script: make ci
  - stage: test
    php: 7.2
    env: JOB=test
    install: make install
    script: make ci
